### ISSUE TITLE
Tried a fresh install with yo!

### ISSUE THREAD

**Issue by jorgeuos** [bezhermoso/generator-docker-drupal-8#1]
Followd the instructions from the readme, got this after answering `? Specify machine name:`

```
events.js:154
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /Users/jorge/.nvm/versions/node/v5.11.0/lib/node_modules/generator-docker-drupal-8/generators/app/templates/.gitignore
    at EditionInterface.exports._copySingle (/Users/jorge/.nvm/versions/node/v5.11.0/lib/node_modules/generator-docker-drupal-8/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/Users/jorge/.nvm/versions/node/v5.11.0/lib/node_modules/generator-docker-drupal-8/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at module.exports.yeoman.Base.extend._promptVagrant.prompting.writing.end._copy (/Users/jorge/.nvm/versions/node/v5.11.0/lib/node_modules/generator-docker-drupal-8/generators/app/index.js:147:16)
    at module.exports.yeoman.Base.extend._promptVagrant.prompting.writing (/Users/jorge/.nvm/versions/node/v5.11.0/lib/node_modules/generator-docker-drupal-8/generators/app/index.js:79:10)
    at Object.<anonymous> (/Users/jorge/.nvm/versions/node/v5.11.0/lib/node_modules/generator-docker-drupal-8/node_modules/yeoman-generator/lib/base.js:431:23)
    at /Users/jorge/.nvm/versions/node/v5.11.0/lib/node_modules/generator-docker-drupal-8/node_modules/run-async/index.js:25:25
    at /Users/jorge/.nvm/versions/node/v5.11.0/lib/node_modules/generator-docker-drupal-8/node_modules/run-async/index.js:24:19
    at /Users/jorge/.nvm/versions/node/v5.11.0/lib/node_modules/generator-docker-drupal-8/node_modules/yeoman-generator/lib/base.js:432:9
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by bezhermoso** [comment]
Hi @jorge-wk,

Thanks for the report! I pushed a hotfix that omits the copying of the `.gitignore` file until I figure out why it's missing in your install. I can verify that it happens on a fresh install, not sure when this started happening.

**Comment by jorgeuos** [comment]
Ok, Great!
